//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.Views.MarketerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marketer", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class Marketer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketerProducts", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class MarketerProducts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eFIN.MVP.Views.MarketerServiceReference.Marketer MarketerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eFIN.MVP.Views.MarketerServiceReference.RelatedProduct[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eFIN.MVP.Views.MarketerServiceReference.Marketer Marketer {
            get {
                return this.MarketerField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketerField, value) != true)) {
                    this.MarketerField = value;
                    this.RaisePropertyChanged("Marketer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eFIN.MVP.Views.MarketerServiceReference.RelatedProduct[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedProduct", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class RelatedProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eFIN.MVP.Views.MarketerServiceReference.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eFIN.MVP.Views.MarketerServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GTINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EAN {
            get {
                return this.EANField;
            }
            set {
                if ((object.ReferenceEquals(this.EANField, value) != true)) {
                    this.EANField = value;
                    this.RaisePropertyChanged("EAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GTIN {
            get {
                return this.GTINField;
            }
            set {
                if ((object.ReferenceEquals(this.GTINField, value) != true)) {
                    this.GTINField = value;
                    this.RaisePropertyChanged("GTIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UOM {
            get {
                return this.UOMField;
            }
            set {
                if ((object.ReferenceEquals(this.UOMField, value) != true)) {
                    this.UOMField = value;
                    this.RaisePropertyChanged("UOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPC {
            get {
                return this.UPCField;
            }
            set {
                if ((object.ReferenceEquals(this.UPCField, value) != true)) {
                    this.UPCField = value;
                    this.RaisePropertyChanged("UPC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductMarketers", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class ProductMarketers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eFIN.MVP.Views.MarketerServiceReference.RelatedMarketer[] MarketersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eFIN.MVP.Views.MarketerServiceReference.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eFIN.MVP.Views.MarketerServiceReference.RelatedMarketer[] Marketers {
            get {
                return this.MarketersField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketersField, value) != true)) {
                    this.MarketersField = value;
                    this.RaisePropertyChanged("Marketers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eFIN.MVP.Views.MarketerServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedMarketer", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class RelatedMarketer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eFIN.MVP.Views.MarketerServiceReference.Marketer MarketerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eFIN.MVP.Views.MarketerServiceReference.Marketer Marketer {
            get {
                return this.MarketerField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketerField, value) != true)) {
                    this.MarketerField = value;
                    this.RaisePropertyChanged("Marketer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarketerServiceReference.IMarketerService")]
    public interface IMarketerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketer", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerResponse")]
        eFIN.MVP.Views.MarketerServiceReference.Marketer GetMarketer(int MarketerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketer", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerResponse")]
        System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.Marketer> GetMarketerAsync(int MarketerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketerId", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerIdResponse")]
        long GetMarketerId(string MarketerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketerId", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerIdResponse")]
        System.Threading.Tasks.Task<long> GetMarketerIdAsync(string MarketerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetAllMarketers", ReplyAction="http://tempuri.org/IMarketerService/GetAllMarketersResponse")]
        eFIN.MVP.Views.MarketerServiceReference.Marketer[] GetAllMarketers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetAllMarketers", ReplyAction="http://tempuri.org/IMarketerService/GetAllMarketersResponse")]
        System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.Marketer[]> GetAllMarketersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetAllMarketersList", ReplyAction="http://tempuri.org/IMarketerService/GetAllMarketersListResponse")]
        eFIN.MVP.Views.MarketerServiceReference.Marketer[] GetAllMarketersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetAllMarketersList", ReplyAction="http://tempuri.org/IMarketerService/GetAllMarketersListResponse")]
        System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.Marketer[]> GetAllMarketersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/SaveMarketer", ReplyAction="http://tempuri.org/IMarketerService/SaveMarketerResponse")]
        long SaveMarketer(string MarketerName, string MarketerDomain, string MarketerType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/SaveMarketer", ReplyAction="http://tempuri.org/IMarketerService/SaveMarketerResponse")]
        System.Threading.Tasks.Task<long> SaveMarketerAsync(string MarketerName, string MarketerDomain, string MarketerType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/DeleteMarketer", ReplyAction="http://tempuri.org/IMarketerService/DeleteMarketerResponse")]
        void DeleteMarketer(string MarketerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/DeleteMarketer", ReplyAction="http://tempuri.org/IMarketerService/DeleteMarketerResponse")]
        System.Threading.Tasks.Task DeleteMarketerAsync(string MarketerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/DeleteMarketerById", ReplyAction="http://tempuri.org/IMarketerService/DeleteMarketerByIdResponse")]
        void DeleteMarketerById(int MarketerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/DeleteMarketerById", ReplyAction="http://tempuri.org/IMarketerService/DeleteMarketerByIdResponse")]
        System.Threading.Tasks.Task DeleteMarketerByIdAsync(int MarketerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/SaveMarketerProduct", ReplyAction="http://tempuri.org/IMarketerService/SaveMarketerProductResponse")]
        void SaveMarketerProduct(string MarketerName, string ProductName, string ProductDescription, string ProductManufacturer, decimal ProductPrice, string ProductSKU, string ProductUPC, string ProductEAN, string ProductGTIN, string ProductUOM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/SaveMarketerProduct", ReplyAction="http://tempuri.org/IMarketerService/SaveMarketerProductResponse")]
        System.Threading.Tasks.Task SaveMarketerProductAsync(string MarketerName, string ProductName, string ProductDescription, string ProductManufacturer, decimal ProductPrice, string ProductSKU, string ProductUPC, string ProductEAN, string ProductGTIN, string ProductUOM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/AddProductToMarketer", ReplyAction="http://tempuri.org/IMarketerService/AddProductToMarketerResponse")]
        void AddProductToMarketer(string MarketerName, string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/AddProductToMarketer", ReplyAction="http://tempuri.org/IMarketerService/AddProductToMarketerResponse")]
        System.Threading.Tasks.Task AddProductToMarketerAsync(string MarketerName, string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/RemoveProductFromMarketer", ReplyAction="http://tempuri.org/IMarketerService/RemoveProductFromMarketerResponse")]
        void RemoveProductFromMarketer(string MarketerName, string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/RemoveProductFromMarketer", ReplyAction="http://tempuri.org/IMarketerService/RemoveProductFromMarketerResponse")]
        System.Threading.Tasks.Task RemoveProductFromMarketerAsync(string MarketerName, string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketerProduct", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerProductResponse")]
        eFIN.MVP.Views.MarketerServiceReference.MarketerProducts GetMarketerProduct(string MarketerName, string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketerProduct", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerProductResponse")]
        System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.MarketerProducts> GetMarketerProductAsync(string MarketerName, string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketerProductId", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerProductIdResponse")]
        long GetMarketerProductId(long MarketerId, long ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketerProductId", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerProductIdResponse")]
        System.Threading.Tasks.Task<long> GetMarketerProductIdAsync(long MarketerId, long ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketerProducts", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerProductsResponse")]
        eFIN.MVP.Views.MarketerServiceReference.MarketerProducts GetMarketerProducts(string MarketerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetMarketerProducts", ReplyAction="http://tempuri.org/IMarketerService/GetMarketerProductsResponse")]
        System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.MarketerProducts> GetMarketerProductsAsync(string MarketerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetProductMarketers", ReplyAction="http://tempuri.org/IMarketerService/GetProductMarketersResponse")]
        eFIN.MVP.Views.MarketerServiceReference.ProductMarketers GetProductMarketers(string ProductName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMarketerService/GetProductMarketers", ReplyAction="http://tempuri.org/IMarketerService/GetProductMarketersResponse")]
        System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.ProductMarketers> GetProductMarketersAsync(string ProductName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarketerServiceChannel : eFIN.MVP.Views.MarketerServiceReference.IMarketerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarketerServiceClient : System.ServiceModel.ClientBase<eFIN.MVP.Views.MarketerServiceReference.IMarketerService>, eFIN.MVP.Views.MarketerServiceReference.IMarketerService {
        
        public MarketerServiceClient() {
        }
        
        public MarketerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarketerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eFIN.MVP.Views.MarketerServiceReference.Marketer GetMarketer(int MarketerId) {
            return base.Channel.GetMarketer(MarketerId);
        }
        
        public System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.Marketer> GetMarketerAsync(int MarketerId) {
            return base.Channel.GetMarketerAsync(MarketerId);
        }
        
        public long GetMarketerId(string MarketerName) {
            return base.Channel.GetMarketerId(MarketerName);
        }
        
        public System.Threading.Tasks.Task<long> GetMarketerIdAsync(string MarketerName) {
            return base.Channel.GetMarketerIdAsync(MarketerName);
        }
        
        public eFIN.MVP.Views.MarketerServiceReference.Marketer[] GetAllMarketers() {
            return base.Channel.GetAllMarketers();
        }
        
        public System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.Marketer[]> GetAllMarketersAsync() {
            return base.Channel.GetAllMarketersAsync();
        }
        
        public eFIN.MVP.Views.MarketerServiceReference.Marketer[] GetAllMarketersList() {
            return base.Channel.GetAllMarketersList();
        }
        
        public System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.Marketer[]> GetAllMarketersListAsync() {
            return base.Channel.GetAllMarketersListAsync();
        }
        
        public long SaveMarketer(string MarketerName, string MarketerDomain, string MarketerType) {
            return base.Channel.SaveMarketer(MarketerName, MarketerDomain, MarketerType);
        }
        
        public System.Threading.Tasks.Task<long> SaveMarketerAsync(string MarketerName, string MarketerDomain, string MarketerType) {
            return base.Channel.SaveMarketerAsync(MarketerName, MarketerDomain, MarketerType);
        }
        
        public void DeleteMarketer(string MarketerName) {
            base.Channel.DeleteMarketer(MarketerName);
        }
        
        public System.Threading.Tasks.Task DeleteMarketerAsync(string MarketerName) {
            return base.Channel.DeleteMarketerAsync(MarketerName);
        }
        
        public void DeleteMarketerById(int MarketerId) {
            base.Channel.DeleteMarketerById(MarketerId);
        }
        
        public System.Threading.Tasks.Task DeleteMarketerByIdAsync(int MarketerId) {
            return base.Channel.DeleteMarketerByIdAsync(MarketerId);
        }
        
        public void SaveMarketerProduct(string MarketerName, string ProductName, string ProductDescription, string ProductManufacturer, decimal ProductPrice, string ProductSKU, string ProductUPC, string ProductEAN, string ProductGTIN, string ProductUOM) {
            base.Channel.SaveMarketerProduct(MarketerName, ProductName, ProductDescription, ProductManufacturer, ProductPrice, ProductSKU, ProductUPC, ProductEAN, ProductGTIN, ProductUOM);
        }
        
        public System.Threading.Tasks.Task SaveMarketerProductAsync(string MarketerName, string ProductName, string ProductDescription, string ProductManufacturer, decimal ProductPrice, string ProductSKU, string ProductUPC, string ProductEAN, string ProductGTIN, string ProductUOM) {
            return base.Channel.SaveMarketerProductAsync(MarketerName, ProductName, ProductDescription, ProductManufacturer, ProductPrice, ProductSKU, ProductUPC, ProductEAN, ProductGTIN, ProductUOM);
        }
        
        public void AddProductToMarketer(string MarketerName, string ProductName) {
            base.Channel.AddProductToMarketer(MarketerName, ProductName);
        }
        
        public System.Threading.Tasks.Task AddProductToMarketerAsync(string MarketerName, string ProductName) {
            return base.Channel.AddProductToMarketerAsync(MarketerName, ProductName);
        }
        
        public void RemoveProductFromMarketer(string MarketerName, string ProductName) {
            base.Channel.RemoveProductFromMarketer(MarketerName, ProductName);
        }
        
        public System.Threading.Tasks.Task RemoveProductFromMarketerAsync(string MarketerName, string ProductName) {
            return base.Channel.RemoveProductFromMarketerAsync(MarketerName, ProductName);
        }
        
        public eFIN.MVP.Views.MarketerServiceReference.MarketerProducts GetMarketerProduct(string MarketerName, string ProductName) {
            return base.Channel.GetMarketerProduct(MarketerName, ProductName);
        }
        
        public System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.MarketerProducts> GetMarketerProductAsync(string MarketerName, string ProductName) {
            return base.Channel.GetMarketerProductAsync(MarketerName, ProductName);
        }
        
        public long GetMarketerProductId(long MarketerId, long ProductId) {
            return base.Channel.GetMarketerProductId(MarketerId, ProductId);
        }
        
        public System.Threading.Tasks.Task<long> GetMarketerProductIdAsync(long MarketerId, long ProductId) {
            return base.Channel.GetMarketerProductIdAsync(MarketerId, ProductId);
        }
        
        public eFIN.MVP.Views.MarketerServiceReference.MarketerProducts GetMarketerProducts(string MarketerName) {
            return base.Channel.GetMarketerProducts(MarketerName);
        }
        
        public System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.MarketerProducts> GetMarketerProductsAsync(string MarketerName) {
            return base.Channel.GetMarketerProductsAsync(MarketerName);
        }
        
        public eFIN.MVP.Views.MarketerServiceReference.ProductMarketers GetProductMarketers(string ProductName) {
            return base.Channel.GetProductMarketers(ProductName);
        }
        
        public System.Threading.Tasks.Task<eFIN.MVP.Views.MarketerServiceReference.ProductMarketers> GetProductMarketersAsync(string ProductName) {
            return base.Channel.GetProductMarketersAsync(ProductName);
        }
    }
}
