//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.Views.Models.AzureDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marketer()
        {
            this.Consumers = new HashSet<Consumer>();
            this.MarketerProducts = new HashSet<MarketerProduct>();
        }
    
        public long marketer_id { get; set; }
        public string marketer_domain { get; set; }
        public string marketer_type { get; set; }
        public string marketer_name { get; set; }
        public System.DateTime marketer_create { get; set; }
        public Nullable<System.DateTime> marketer_update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumer> Consumers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketerProduct> MarketerProducts { get; set; }
    }
}
