//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.Views.Models.AzureDataModels
{
    using System;

    public partial class OfferMatch
    {
        public long offermatch_id { get; set; }
        public long consumeroffer_id { get; set; }
        public long supplieroffer_id { get; set; }
        public System.DateTime offermatch_createdate { get; set; }
        public Nullable<System.DateTime> offermatch_update { get; set; }
    
        public virtual ConsumerOffer ConsumerOffer { get; set; }
        public virtual SupplierOffer SupplierOffer { get; set; }
    }
}
