//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.Views.Models.AzureDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierProduct()
        {
            this.SupplierOffers = new HashSet<SupplierOffer>();
        }
    
        public long supplierproduct_id { get; set; }
        public long supplier_id { get; set; }
        public long product_id { get; set; }
        public Nullable<System.DateTime> supplierproduct_create { get; set; }
        public Nullable<System.DateTime> supplierproduct_update { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierOffer> SupplierOffers { get; set; }
    }
}
