//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.Views.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ursCoreEntities : DbContext
    {
        public ursCoreEntities()
            : base("name=ursCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Consumer> Consumers { get; set; }
        public virtual DbSet<ConsumerOffer> ConsumerOffers { get; set; }
        public virtual DbSet<Marketer> Marketers { get; set; }
        public virtual DbSet<MarketerProduct> MarketerProducts { get; set; }
        public virtual DbSet<OfferMatch> OfferMatches { get; set; }
        public virtual DbSet<OfferStatu> OfferStatus { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierOffer> SupplierOffers { get; set; }
        public virtual DbSet<SupplierProduct> SupplierProducts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
