//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.Views.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketerProduct
    {
        public long marketerproduct_id { get; set; }
        public long marketer_id { get; set; }
        public long product_id { get; set; }
        public Nullable<System.DateTime> marketerproduct_create { get; set; }
        public Nullable<System.DateTime> marketerproduct_update { get; set; }
    
        public virtual Marketer Marketer { get; set; }
        public virtual Product Product { get; set; }
    }
}
