//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.AzureEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressEntity
    {
        public long address_id { get; set; }
        public string line_1 { get; set; }
        public string line_2 { get; set; }
        public string line_3 { get; set; }
        public string city { get; set; }
        public string zip_postal_code { get; set; }
        public string state_province_county { get; set; }
        public string country { get; set; }
        public System.DateTime address_create { get; set; }
        public Nullable<System.DateTime> address_update { get; set; }
    }
}
