//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.AzureEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsumerEntity()
        {
            this.ConsumerOffers = new HashSet<ConsumerOfferEntity>();
        }
    
        public long consumer_id { get; set; }
        public long marketer_id { get; set; }
        public long bill_address_id { get; set; }
        public long ship_address_id { get; set; }
        public string consumer_handle { get; set; }
        public string consumer_email { get; set; }
        public string consumer_fname { get; set; }
        public string consumer_mname { get; set; }
        public string consumer_lname { get; set; }
        public string consumer_phone { get; set; }
        public string consumer_status { get; set; }
        public System.DateTime consumer_create { get; set; }
        public Nullable<System.DateTime> consumer_update { get; set; }
    
        public virtual AddressEntity BillingAddress { get; set; }
        public virtual AddressEntity ShippingAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerOfferEntity> ConsumerOffers { get; set; }
        public virtual MarketerEntity Marketer { get; set; }
    }
}
