//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.AzureEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ursCoreMVPEntities : DbContext
    {
        public ursCoreMVPEntities()
            : base("name=ursCoreMVPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressEntity> AddressEntities { get; set; }
        public virtual DbSet<ConsumerEntity> ConsumerEntities { get; set; }
        public virtual DbSet<ConsumerOfferEntity> ConsumerOfferEntities { get; set; }
        public virtual DbSet<MarketerEntity> MarketerEntities { get; set; }
        public virtual DbSet<MarketerProductEntity> MarketerProductEntities { get; set; }
        public virtual DbSet<OfferMatchEntity> OfferMatchEntities { get; set; }
        public virtual DbSet<OfferStatusEntity> OfferStatusEntities { get; set; }
        public virtual DbSet<ProductEntity> ProductEntities { get; set; }
        public virtual DbSet<SupplierEntity> SupplierEntities { get; set; }
        public virtual DbSet<SupplierOfferEntity> SupplierOfferEntities { get; set; }
        public virtual DbSet<SupplierProductEntity> SupplierProductEntities { get; set; }
    }
}
