//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.AzureEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferMatchEntity
    {
        public long offermatch_id { get; set; }
        public long consumeroffer_id { get; set; }
        public long supplieroffer_id { get; set; }
        public System.DateTime offermatch_createdate { get; set; }
        public Nullable<System.DateTime> offermatch_update { get; set; }
    
        public virtual ConsumerOfferEntity ConsumerOffer { get; set; }
        public virtual SupplierOfferEntity SupplierOffer { get; set; }
    }
}
