//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.AzureEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferStatusEntity
    {
        public long offer_status_id { get; set; }
        public string offer_status { get; set; }
        public string offer_status_description { get; set; }
        public Nullable<System.DateTime> offer_status_update { get; set; }
    }
}
