//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFIN.MVP.AzureEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductEntity()
        {
            this.MarketerProducts = new HashSet<MarketerProductEntity>();
            this.SupplierProducts = new HashSet<SupplierProductEntity>();
        }
    
        public long product_id { get; set; }
        public string product_manufacturer { get; set; }
        public string product_sku { get; set; }
        public string product_upc { get; set; }
        public string product_ean { get; set; }
        public string product_gtin { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public string product_uom { get; set; }
        public decimal product_price { get; set; }
        public System.DateTime product_create { get; set; }
        public Nullable<System.DateTime> product_update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketerProductEntity> MarketerProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierProductEntity> SupplierProducts { get; set; }
    }
}
