//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urShopper.Data.Loader.ConsumerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consumer", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class Consumer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private urShopper.Data.Loader.ConsumerService.Address BillAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BillAddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerHandleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ConsumerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerMNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private urShopper.Data.Loader.ConsumerService.Marketer MarketerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MarketerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private urShopper.Data.Loader.ConsumerService.Address ShipAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShipAddressIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public urShopper.Data.Loader.ConsumerService.Address BillAddress {
            get {
                return this.BillAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BillAddressField, value) != true)) {
                    this.BillAddressField = value;
                    this.RaisePropertyChanged("BillAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillAddressId {
            get {
                return this.BillAddressIdField;
            }
            set {
                if ((this.BillAddressIdField.Equals(value) != true)) {
                    this.BillAddressIdField = value;
                    this.RaisePropertyChanged("BillAddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerEmail {
            get {
                return this.ConsumerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerEmailField, value) != true)) {
                    this.ConsumerEmailField = value;
                    this.RaisePropertyChanged("ConsumerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerFName {
            get {
                return this.ConsumerFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerFNameField, value) != true)) {
                    this.ConsumerFNameField = value;
                    this.RaisePropertyChanged("ConsumerFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerHandle {
            get {
                return this.ConsumerHandleField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerHandleField, value) != true)) {
                    this.ConsumerHandleField = value;
                    this.RaisePropertyChanged("ConsumerHandle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ConsumerId {
            get {
                return this.ConsumerIdField;
            }
            set {
                if ((this.ConsumerIdField.Equals(value) != true)) {
                    this.ConsumerIdField = value;
                    this.RaisePropertyChanged("ConsumerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerLName {
            get {
                return this.ConsumerLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerLNameField, value) != true)) {
                    this.ConsumerLNameField = value;
                    this.RaisePropertyChanged("ConsumerLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerMName {
            get {
                return this.ConsumerMNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerMNameField, value) != true)) {
                    this.ConsumerMNameField = value;
                    this.RaisePropertyChanged("ConsumerMName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerName {
            get {
                return this.ConsumerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerNameField, value) != true)) {
                    this.ConsumerNameField = value;
                    this.RaisePropertyChanged("ConsumerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerPhone {
            get {
                return this.ConsumerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerPhoneField, value) != true)) {
                    this.ConsumerPhoneField = value;
                    this.RaisePropertyChanged("ConsumerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerStatus {
            get {
                return this.ConsumerStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerStatusField, value) != true)) {
                    this.ConsumerStatusField = value;
                    this.RaisePropertyChanged("ConsumerStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public urShopper.Data.Loader.ConsumerService.Marketer Marketer {
            get {
                return this.MarketerField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketerField, value) != true)) {
                    this.MarketerField = value;
                    this.RaisePropertyChanged("Marketer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MarketerId {
            get {
                return this.MarketerIdField;
            }
            set {
                if ((this.MarketerIdField.Equals(value) != true)) {
                    this.MarketerIdField = value;
                    this.RaisePropertyChanged("MarketerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public urShopper.Data.Loader.ConsumerService.Address ShipAddress {
            get {
                return this.ShipAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipAddressField, value) != true)) {
                    this.ShipAddressField = value;
                    this.RaisePropertyChanged("ShipAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShipAddressId {
            get {
                return this.ShipAddressIdField;
            }
            set {
                if ((this.ShipAddressIdField.Equals(value) != true)) {
                    this.ShipAddressIdField = value;
                    this.RaisePropertyChanged("ShipAddressId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateProvinceCountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipPostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvinceCounty {
            get {
                return this.StateProvinceCountyField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceCountyField, value) != true)) {
                    this.StateProvinceCountyField = value;
                    this.RaisePropertyChanged("StateProvinceCounty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipPostalCode {
            get {
                return this.ZipPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipPostalCodeField, value) != true)) {
                    this.ZipPostalCodeField = value;
                    this.RaisePropertyChanged("ZipPostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marketer", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class Marketer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsumerOffer", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class ConsumerOffer : urShopper.Data.Loader.ConsumerService.Offer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ConsumerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MarketerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private urShopper.Data.Loader.ConsumerService.Consumer OfferedConsumerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private urShopper.Data.Loader.ConsumerService.Offer[] OffersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ConsumerId {
            get {
                return this.ConsumerIdField;
            }
            set {
                if ((this.ConsumerIdField.Equals(value) != true)) {
                    this.ConsumerIdField = value;
                    this.RaisePropertyChanged("ConsumerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MarketerId {
            get {
                return this.MarketerIdField;
            }
            set {
                if ((this.MarketerIdField.Equals(value) != true)) {
                    this.MarketerIdField = value;
                    this.RaisePropertyChanged("MarketerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public urShopper.Data.Loader.ConsumerService.Consumer OfferedConsumer {
            get {
                return this.OfferedConsumerField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferedConsumerField, value) != true)) {
                    this.OfferedConsumerField = value;
                    this.RaisePropertyChanged("OfferedConsumer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public urShopper.Data.Loader.ConsumerService.Offer[] Offers {
            get {
                return this.OffersField;
            }
            set {
                if ((object.ReferenceEquals(this.OffersField, value) != true)) {
                    this.OffersField = value;
                    this.RaisePropertyChanged("Offers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offer", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(urShopper.Data.Loader.ConsumerService.ConsumerOffer))]
    public partial class Offer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrentOfferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MarketerProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaxPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OfferDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OfferIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private urShopper.Data.Loader.ConsumerService.Product OfferedProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long StatusIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrentOffer {
            get {
                return this.IsCurrentOfferField;
            }
            set {
                if ((this.IsCurrentOfferField.Equals(value) != true)) {
                    this.IsCurrentOfferField = value;
                    this.RaisePropertyChanged("IsCurrentOffer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MarketerProductId {
            get {
                return this.MarketerProductIdField;
            }
            set {
                if ((this.MarketerProductIdField.Equals(value) != true)) {
                    this.MarketerProductIdField = value;
                    this.RaisePropertyChanged("MarketerProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxPrice {
            get {
                return this.MaxPriceField;
            }
            set {
                if ((this.MaxPriceField.Equals(value) != true)) {
                    this.MaxPriceField = value;
                    this.RaisePropertyChanged("MaxPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OfferDate {
            get {
                return this.OfferDateField;
            }
            set {
                if ((this.OfferDateField.Equals(value) != true)) {
                    this.OfferDateField = value;
                    this.RaisePropertyChanged("OfferDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OfferId {
            get {
                return this.OfferIdField;
            }
            set {
                if ((this.OfferIdField.Equals(value) != true)) {
                    this.OfferIdField = value;
                    this.RaisePropertyChanged("OfferId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public urShopper.Data.Loader.ConsumerService.Product OfferedProduct {
            get {
                return this.OfferedProductField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferedProductField, value) != true)) {
                    this.OfferedProductField = value;
                    this.RaisePropertyChanged("OfferedProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/eFIN.MVP.Services.Store")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GTINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EAN {
            get {
                return this.EANField;
            }
            set {
                if ((object.ReferenceEquals(this.EANField, value) != true)) {
                    this.EANField = value;
                    this.RaisePropertyChanged("EAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GTIN {
            get {
                return this.GTINField;
            }
            set {
                if ((object.ReferenceEquals(this.GTINField, value) != true)) {
                    this.GTINField = value;
                    this.RaisePropertyChanged("GTIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedOn {
            get {
                return this.LastUpdatedOnField;
            }
            set {
                if ((this.LastUpdatedOnField.Equals(value) != true)) {
                    this.LastUpdatedOnField = value;
                    this.RaisePropertyChanged("LastUpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UOM {
            get {
                return this.UOMField;
            }
            set {
                if ((object.ReferenceEquals(this.UOMField, value) != true)) {
                    this.UOMField = value;
                    this.RaisePropertyChanged("UOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPC {
            get {
                return this.UPCField;
            }
            set {
                if ((object.ReferenceEquals(this.UPCField, value) != true)) {
                    this.UPCField = value;
                    this.RaisePropertyChanged("UPC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsumerService.IConsumerService")]
    public interface IConsumerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetConsumer", ReplyAction="http://tempuri.org/IConsumerService/GetConsumerResponse")]
        urShopper.Data.Loader.ConsumerService.Consumer GetConsumer(string ConsumerHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetConsumer", ReplyAction="http://tempuri.org/IConsumerService/GetConsumerResponse")]
        System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.Consumer> GetConsumerAsync(string ConsumerHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetConsumerById", ReplyAction="http://tempuri.org/IConsumerService/GetConsumerByIdResponse")]
        urShopper.Data.Loader.ConsumerService.Consumer GetConsumerById(long ConsumerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetConsumerById", ReplyAction="http://tempuri.org/IConsumerService/GetConsumerByIdResponse")]
        System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.Consumer> GetConsumerByIdAsync(long ConsumerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetConsumerId", ReplyAction="http://tempuri.org/IConsumerService/GetConsumerIdResponse")]
        long GetConsumerId(string ConsumerHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetConsumerId", ReplyAction="http://tempuri.org/IConsumerService/GetConsumerIdResponse")]
        System.Threading.Tasks.Task<long> GetConsumerIdAsync(string ConsumerHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetAllConsumers", ReplyAction="http://tempuri.org/IConsumerService/GetAllConsumersResponse")]
        urShopper.Data.Loader.ConsumerService.Consumer[] GetAllConsumers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetAllConsumers", ReplyAction="http://tempuri.org/IConsumerService/GetAllConsumersResponse")]
        System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.Consumer[]> GetAllConsumersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetAllConsumersList", ReplyAction="http://tempuri.org/IConsumerService/GetAllConsumersListResponse")]
        urShopper.Data.Loader.ConsumerService.Consumer[] GetAllConsumersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetAllConsumersList", ReplyAction="http://tempuri.org/IConsumerService/GetAllConsumersListResponse")]
        System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.Consumer[]> GetAllConsumersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveMarketerConsumer", ReplyAction="http://tempuri.org/IConsumerService/SaveMarketerConsumerResponse")]
        long SaveMarketerConsumer(string MarketerName, string MarkterDomain, string MarketerType, string ConsumerHandle, string ConsumerEmail, string ConsumerFName, string ConsumerMName, string ConsumerLName, string ConsumerPhone, string ConsumerStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveMarketerConsumer", ReplyAction="http://tempuri.org/IConsumerService/SaveMarketerConsumerResponse")]
        System.Threading.Tasks.Task<long> SaveMarketerConsumerAsync(string MarketerName, string MarkterDomain, string MarketerType, string ConsumerHandle, string ConsumerEmail, string ConsumerFName, string ConsumerMName, string ConsumerLName, string ConsumerPhone, string ConsumerStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveConsumer", ReplyAction="http://tempuri.org/IConsumerService/SaveConsumerResponse")]
        long SaveConsumer(string MarketerName, string ConsumerHandle, string ConsumerEmail, string ConsumerFName, string ConsumerMName, string ConsumerLName, string ConsumerPhone, string ConsumerStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveConsumer", ReplyAction="http://tempuri.org/IConsumerService/SaveConsumerResponse")]
        System.Threading.Tasks.Task<long> SaveConsumerAsync(string MarketerName, string ConsumerHandle, string ConsumerEmail, string ConsumerFName, string ConsumerMName, string ConsumerLName, string ConsumerPhone, string ConsumerStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveConsumerBillingAddress", ReplyAction="http://tempuri.org/IConsumerService/SaveConsumerBillingAddressResponse")]
        long SaveConsumerBillingAddress(string ConsumerHandle, string Line1, string Line2, string Line3, string City, string ZipPostalCode, string StateProvinceCounty, string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveConsumerBillingAddress", ReplyAction="http://tempuri.org/IConsumerService/SaveConsumerBillingAddressResponse")]
        System.Threading.Tasks.Task<long> SaveConsumerBillingAddressAsync(string ConsumerHandle, string Line1, string Line2, string Line3, string City, string ZipPostalCode, string StateProvinceCounty, string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveConsumerShippingAddress", ReplyAction="http://tempuri.org/IConsumerService/SaveConsumerShippingAddressResponse")]
        long SaveConsumerShippingAddress(string ConsumerHandle, string Line1, string Line2, string Line3, string City, string ZipPostalCode, string StateProvinceCounty, string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveConsumerShippingAddress", ReplyAction="http://tempuri.org/IConsumerService/SaveConsumerShippingAddressResponse")]
        System.Threading.Tasks.Task<long> SaveConsumerShippingAddressAsync(string ConsumerHandle, string Line1, string Line2, string Line3, string City, string ZipPostalCode, string StateProvinceCounty, string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/DeleteConsumer", ReplyAction="http://tempuri.org/IConsumerService/DeleteConsumerResponse")]
        void DeleteConsumer(string ConsumerHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/DeleteConsumer", ReplyAction="http://tempuri.org/IConsumerService/DeleteConsumerResponse")]
        System.Threading.Tasks.Task DeleteConsumerAsync(string ConsumerHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/DeleteConsumerById", ReplyAction="http://tempuri.org/IConsumerService/DeleteConsumerByIdResponse")]
        void DeleteConsumerById(int ConsumerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/DeleteConsumerById", ReplyAction="http://tempuri.org/IConsumerService/DeleteConsumerByIdResponse")]
        System.Threading.Tasks.Task DeleteConsumerByIdAsync(int ConsumerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetConsumerOffers", ReplyAction="http://tempuri.org/IConsumerService/GetConsumerOffersResponse")]
        urShopper.Data.Loader.ConsumerService.ConsumerOffer[] GetConsumerOffers(string MarketerName, string ConsumerHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/GetConsumerOffers", ReplyAction="http://tempuri.org/IConsumerService/GetConsumerOffersResponse")]
        System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.ConsumerOffer[]> GetConsumerOffersAsync(string MarketerName, string ConsumerHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveConsumerOffer", ReplyAction="http://tempuri.org/IConsumerService/SaveConsumerOfferResponse")]
        long SaveConsumerOffer(string ConsumerHandle, string MarketerName, string ProductSKU, System.DateTime ConsumerOfferDate, System.DateTime OfferValidUpto, int ConsumerOfferQty, decimal ConsumerOfferMaxPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumerService/SaveConsumerOffer", ReplyAction="http://tempuri.org/IConsumerService/SaveConsumerOfferResponse")]
        System.Threading.Tasks.Task<long> SaveConsumerOfferAsync(string ConsumerHandle, string MarketerName, string ProductSKU, System.DateTime ConsumerOfferDate, System.DateTime OfferValidUpto, int ConsumerOfferQty, decimal ConsumerOfferMaxPrice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsumerServiceChannel : urShopper.Data.Loader.ConsumerService.IConsumerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsumerServiceClient : System.ServiceModel.ClientBase<urShopper.Data.Loader.ConsumerService.IConsumerService>, urShopper.Data.Loader.ConsumerService.IConsumerService {
        
        public ConsumerServiceClient() {
        }
        
        public ConsumerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsumerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public urShopper.Data.Loader.ConsumerService.Consumer GetConsumer(string ConsumerHandle) {
            return base.Channel.GetConsumer(ConsumerHandle);
        }
        
        public System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.Consumer> GetConsumerAsync(string ConsumerHandle) {
            return base.Channel.GetConsumerAsync(ConsumerHandle);
        }
        
        public urShopper.Data.Loader.ConsumerService.Consumer GetConsumerById(long ConsumerId) {
            return base.Channel.GetConsumerById(ConsumerId);
        }
        
        public System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.Consumer> GetConsumerByIdAsync(long ConsumerId) {
            return base.Channel.GetConsumerByIdAsync(ConsumerId);
        }
        
        public long GetConsumerId(string ConsumerHandle) {
            return base.Channel.GetConsumerId(ConsumerHandle);
        }
        
        public System.Threading.Tasks.Task<long> GetConsumerIdAsync(string ConsumerHandle) {
            return base.Channel.GetConsumerIdAsync(ConsumerHandle);
        }
        
        public urShopper.Data.Loader.ConsumerService.Consumer[] GetAllConsumers() {
            return base.Channel.GetAllConsumers();
        }
        
        public System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.Consumer[]> GetAllConsumersAsync() {
            return base.Channel.GetAllConsumersAsync();
        }
        
        public urShopper.Data.Loader.ConsumerService.Consumer[] GetAllConsumersList() {
            return base.Channel.GetAllConsumersList();
        }
        
        public System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.Consumer[]> GetAllConsumersListAsync() {
            return base.Channel.GetAllConsumersListAsync();
        }
        
        public long SaveMarketerConsumer(string MarketerName, string MarkterDomain, string MarketerType, string ConsumerHandle, string ConsumerEmail, string ConsumerFName, string ConsumerMName, string ConsumerLName, string ConsumerPhone, string ConsumerStatus) {
            return base.Channel.SaveMarketerConsumer(MarketerName, MarkterDomain, MarketerType, ConsumerHandle, ConsumerEmail, ConsumerFName, ConsumerMName, ConsumerLName, ConsumerPhone, ConsumerStatus);
        }
        
        public System.Threading.Tasks.Task<long> SaveMarketerConsumerAsync(string MarketerName, string MarkterDomain, string MarketerType, string ConsumerHandle, string ConsumerEmail, string ConsumerFName, string ConsumerMName, string ConsumerLName, string ConsumerPhone, string ConsumerStatus) {
            return base.Channel.SaveMarketerConsumerAsync(MarketerName, MarkterDomain, MarketerType, ConsumerHandle, ConsumerEmail, ConsumerFName, ConsumerMName, ConsumerLName, ConsumerPhone, ConsumerStatus);
        }
        
        public long SaveConsumer(string MarketerName, string ConsumerHandle, string ConsumerEmail, string ConsumerFName, string ConsumerMName, string ConsumerLName, string ConsumerPhone, string ConsumerStatus) {
            return base.Channel.SaveConsumer(MarketerName, ConsumerHandle, ConsumerEmail, ConsumerFName, ConsumerMName, ConsumerLName, ConsumerPhone, ConsumerStatus);
        }
        
        public System.Threading.Tasks.Task<long> SaveConsumerAsync(string MarketerName, string ConsumerHandle, string ConsumerEmail, string ConsumerFName, string ConsumerMName, string ConsumerLName, string ConsumerPhone, string ConsumerStatus) {
            return base.Channel.SaveConsumerAsync(MarketerName, ConsumerHandle, ConsumerEmail, ConsumerFName, ConsumerMName, ConsumerLName, ConsumerPhone, ConsumerStatus);
        }
        
        public long SaveConsumerBillingAddress(string ConsumerHandle, string Line1, string Line2, string Line3, string City, string ZipPostalCode, string StateProvinceCounty, string Country) {
            return base.Channel.SaveConsumerBillingAddress(ConsumerHandle, Line1, Line2, Line3, City, ZipPostalCode, StateProvinceCounty, Country);
        }
        
        public System.Threading.Tasks.Task<long> SaveConsumerBillingAddressAsync(string ConsumerHandle, string Line1, string Line2, string Line3, string City, string ZipPostalCode, string StateProvinceCounty, string Country) {
            return base.Channel.SaveConsumerBillingAddressAsync(ConsumerHandle, Line1, Line2, Line3, City, ZipPostalCode, StateProvinceCounty, Country);
        }
        
        public long SaveConsumerShippingAddress(string ConsumerHandle, string Line1, string Line2, string Line3, string City, string ZipPostalCode, string StateProvinceCounty, string Country) {
            return base.Channel.SaveConsumerShippingAddress(ConsumerHandle, Line1, Line2, Line3, City, ZipPostalCode, StateProvinceCounty, Country);
        }
        
        public System.Threading.Tasks.Task<long> SaveConsumerShippingAddressAsync(string ConsumerHandle, string Line1, string Line2, string Line3, string City, string ZipPostalCode, string StateProvinceCounty, string Country) {
            return base.Channel.SaveConsumerShippingAddressAsync(ConsumerHandle, Line1, Line2, Line3, City, ZipPostalCode, StateProvinceCounty, Country);
        }
        
        public void DeleteConsumer(string ConsumerHandle) {
            base.Channel.DeleteConsumer(ConsumerHandle);
        }
        
        public System.Threading.Tasks.Task DeleteConsumerAsync(string ConsumerHandle) {
            return base.Channel.DeleteConsumerAsync(ConsumerHandle);
        }
        
        public void DeleteConsumerById(int ConsumerId) {
            base.Channel.DeleteConsumerById(ConsumerId);
        }
        
        public System.Threading.Tasks.Task DeleteConsumerByIdAsync(int ConsumerId) {
            return base.Channel.DeleteConsumerByIdAsync(ConsumerId);
        }
        
        public urShopper.Data.Loader.ConsumerService.ConsumerOffer[] GetConsumerOffers(string MarketerName, string ConsumerHandle) {
            return base.Channel.GetConsumerOffers(MarketerName, ConsumerHandle);
        }
        
        public System.Threading.Tasks.Task<urShopper.Data.Loader.ConsumerService.ConsumerOffer[]> GetConsumerOffersAsync(string MarketerName, string ConsumerHandle) {
            return base.Channel.GetConsumerOffersAsync(MarketerName, ConsumerHandle);
        }
        
        public long SaveConsumerOffer(string ConsumerHandle, string MarketerName, string ProductSKU, System.DateTime ConsumerOfferDate, System.DateTime OfferValidUpto, int ConsumerOfferQty, decimal ConsumerOfferMaxPrice) {
            return base.Channel.SaveConsumerOffer(ConsumerHandle, MarketerName, ProductSKU, ConsumerOfferDate, OfferValidUpto, ConsumerOfferQty, ConsumerOfferMaxPrice);
        }
        
        public System.Threading.Tasks.Task<long> SaveConsumerOfferAsync(string ConsumerHandle, string MarketerName, string ProductSKU, System.DateTime ConsumerOfferDate, System.DateTime OfferValidUpto, int ConsumerOfferQty, decimal ConsumerOfferMaxPrice) {
            return base.Channel.SaveConsumerOfferAsync(ConsumerHandle, MarketerName, ProductSKU, ConsumerOfferDate, OfferValidUpto, ConsumerOfferQty, ConsumerOfferMaxPrice);
        }
    }
}
